// ─────────────────────────────────────────────────────────────────────────────
// video/store.mjs — durable-enough live state for a video-assembly job in Redis.
//
// Mirrors the existing redis.js "live job" pattern but for the parallel engine,
// where many workers write CONCURRENTLY. To stay race-free without Lua:
//   • the job plan/status is one JSON key (vjob:{id}) — written only by the
//     orchestrator + the check worker (low contention);
//   • each scene's assets live in their OWN Redis HASH (vjob:{id}:scene:{i}) so
//     the audio worker and the visual worker write DISJOINT fields (HSET is
//     atomic per-field — no read-modify-write clobber);
//   • batch dispatch + stitch are guarded by atomic SADD / SET-NX so exactly one
//     worker ever advances a batch or kicks off the stitch.
// ─────────────────────────────────────────────────────────────────────────────
import { sharedConnection } from "./connection.mjs";

const TTL = 60 * 60 * 24; // 24h
const jobKey = (id) => `vjob:${id}`;
const sceneKey = (id, i) => `vjob:${id}:scene:${i}`;
const batchGuardKey = (id) => `vjob:${id}:dispatched`;
const stitchGuardKey = (id) => `vjob:${id}:stitch`;

function r() { return sharedConnection(); }

// ── Generated-asset cache (cross-job reuse) ──────────────────────────────────
// A whiteboard icon/raster generated by Recraft for a given asset_query is SAVED here so the
// SAME query never re-hits the paid generator again — in this job OR any future job. Keyed by
// a canonical slug of the query (+ kind). Long TTL; best-effort (a cache miss/error just
// regenerates). The durable shared library (R2/Postgres + embeddings) is the later upgrade.
function assetSlug(query) {
  return String(query || "").toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80) || "unknown";
}
export function assetCacheKey(kind, query) { return `wbasset:v1:${kind}:${assetSlug(query)}`; }
// DURABLE layer (Guide-2 §I/§T #7): generated assets also land in object storage (R2), so they
// survive a Redis flush AND are reusable across deploys — a real "generated asset manifest", not
// just a hot cache. Lazy + guarded: no R2 configured → Redis-only (unchanged behaviour).
const assetR2Key = (kind, query) => `whiteboard/assets/v1/${kind}/${assetSlug(query)}.json`;
async function durableStore() {
  try { const s = await import("../storage.mjs"); return s.isConfigured?.() ? s : null; } catch { return null; }
}

// Big blobs (raster b64 — a flux hero is ~200KB–1MB) must NOT live in Redis: they balloon the
// instance toward the fixed-plan STORAGE CAP (e.g. 250MB). Keep those in the DURABLE R2 layer only;
// Redis caches just the small vector/metadata assets. R2 holds everything (durable + cheap + huge).
const REDIS_ASSET_MAX = 48 * 1024; // bytes of JSON; above this → R2-only

export async function getCachedAsset(kind, query) {
  try { const v = await r().get(assetCacheKey(kind, query)); if (v) return JSON.parse(v); } catch { /* fall through */ }
  // Redis miss → try the durable R2 manifest; on hit, warm Redis back up ONLY if small enough.
  try {
    const s = await durableStore();
    if (s) {
      const buf = await s.downloadBytes(assetR2Key(kind, query)).catch(() => null);
      if (buf) {
        const val = JSON.parse(buf.toString("utf8"));
        if (buf.length <= REDIS_ASSET_MAX) r().set(assetCacheKey(kind, query), JSON.stringify(val), "EX", 180 * 86400).catch(() => {});
        return val;
      }
    }
  } catch { /* durable is best-effort */ }
  return null;
}
export async function setCachedAsset(kind, query, value, ttlSeconds = 180 * 86400) {
  const json = JSON.stringify(value);
  // small (icon/metadata) → Redis hot cache + R2; big (raster) → R2 ONLY so Redis stays under the cap.
  if (json.length <= REDIS_ASSET_MAX) {
    try { await r().set(assetCacheKey(kind, query), json, "EX", ttlSeconds); } catch { /* hot cache best-effort */ }
  }
  try { const s = await durableStore(); if (s) await s.uploadBytes(assetR2Key(kind, query), Buffer.from(json), "application/json"); }
  catch { /* durable best-effort */ }
}

// ── Whiteboard PLAN cache (cross-job reuse) ──────────────────────────────────
// The LLM Visual Director output (whiteboard_visual_plan) for a given scene is SAVED so a
// re-run of the SAME script never re-hits the (paid) LLM again. Keyed by genre + duration +
// a stable hash of the narration (tenant-agnostic: the plan is derived purely from those).
// Stores the RAW plan (pre-asset-baking) so the value stays small; the asset cache handles
// the (separate) Recraft reuse. Shorter TTL than assets — scripts churn more.
function _planSlug({ genre, duration, narration }) {
  let h = 5381; const s = String(narration || "");
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0; // djb2
  const g = String(genre || "lineart").toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const d = Math.round(Number(duration) || 0);
  return `${g}:${d}:${(h >>> 0).toString(36)}`;
}
export function planCacheKey(parts) { return `wbplan:v2:${_planSlug(parts)}`; }
export async function getCachedPlan(parts) {
  try { const v = await r().get(planCacheKey(parts)); return v ? JSON.parse(v) : null; }
  catch { return null; }
}
export async function setCachedPlan(parts, plan, ttlSeconds = 30 * 86400) {
  try { await r().set(planCacheKey(parts), JSON.stringify(plan), "EX", ttlSeconds); }
  catch { /* cache is best-effort */ }
}

// scene is "ready to stitch" when its narration exists and a visual exists
// (a clip that fell back to an image counts as ready).
export function sceneComplete(scene) {
  return (
    scene &&
    (scene.audioStatus === "done" || scene.audioStatus === "fallback") &&   // "fallback" = silent track
    (scene.visualStatus === "done" || scene.visualStatus === "fallback")
  );
}
export function sceneFailed(scene) {
  return scene && (scene.audioStatus === "failed" || scene.visualStatus === "failed");
}

// Map a segmenter scene → its visual kind. Accepts the Python segmenter's
// snake_case (clip_eligible) AND camelCase (clipEligible); explicit `kind` wins.
export function sceneKind(scene) {
  return scene.kind ?? ((scene.clipEligible ?? scene.clip_eligible) ? "clip" : "image");
}

/** Create the job JSON + one hash per scene. */
export async function createJob(job) {
  const { jobId, scenes = [] } = job;
  const meta = { ...job };
  delete meta.scenes;
  meta.createdAt = meta.createdAt || Date.now();
  meta.status = meta.status || "queued";
  const pipe = r().pipeline();
  pipe.set(jobKey(jobId), JSON.stringify(meta), "EX", TTL);
  scenes.forEach((s, i) => {
    pipe.hset(sceneKey(jobId, i), {
      number: String(s.number ?? i + 1),
      text: s.text ?? "",
      visualPrompt: s.visualPrompt ?? s.visual_prompt ?? "",
      kind: sceneKind(s),
      estSeconds: String(s.estSeconds ?? s.est_seconds ?? 0),
      audioStatus: "pending",
      visualStatus: "pending",
    });
    pipe.expire(sceneKey(jobId, i), TTL);
  });
  await pipe.exec();
  return meta;
}

export async function getMeta(jobId) {
  const raw = await r().get(jobKey(jobId));
  return raw ? JSON.parse(raw) : null;
}

/** List a tenant's recent video jobs (newest first) for the server-backed "Video saya" history.
 * Scans vjob:* (bounded by TTL) + filters by tenant. Fine at launch volume; add a per-tenant index
 * if it grows. */
export async function listTenantJobs(tenantId, limit = 24) {
  let keys = [];
  try { keys = await r().keys("vjob:*"); } catch { return []; }
  const metaKeys = keys.filter((k) => /^vjob:[^:]+$/.test(k)); // skip :scene:/:stitch/:dispatched/…
  const out = [];
  for (const k of metaKeys) {
    let raw; try { raw = await r().get(k); } catch { continue; }
    if (!raw) continue;
    let m; try { m = JSON.parse(raw); } catch { continue; }
    if (m.tenantId !== tenantId) continue;
    out.push({ jobId: k.slice("vjob:".length), status: m.status, sceneCount: m.sceneCount,
      createdAt: m.createdAt, mp4Key: m.mp4Key, durationActual: m.durationActual,
      visualMode: m.visualMode, whiteboardGenre: m.whiteboardGenre });
  }
  out.sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0));
  return out.slice(0, limit);
}

/** Merge a partial into the job JSON (orchestrator/check only). */
export async function patchMeta(jobId, partial) {
  const cur = (await getMeta(jobId)) || {};
  const next = { ...cur, ...partial };
  await r().set(jobKey(jobId), JSON.stringify(next), "EX", TTL);
  return next;
}

export async function setStatus(jobId, status, extra = {}) {
  const next = await patchMeta(jobId, { status, ...extra });
  // Phase 3: release the tenant's concurrency slot the moment a job goes terminal.
  // setStatus is the single status chokepoint, so this covers EVERY path (orchestrator
  // done/fail + the cancel endpoint). release() is idempotent, so double-fire is safe.
  if (next?.tenantId && (status === "done" || status === "failed" || status === "canceled")) {
    try {
      const { release, releaseGlobal } = await import("./concurrency.mjs");
      await release(next.tenantId, jobId);   // per-tenant slot
      await releaseGlobal(jobId);            // global admission slot (Change 2)
    } catch { /* non-fatal — a stranded slot self-heals via its TTL */ }
  }
  return next;
}

/** Write disjoint scene fields (HSET, atomic per field). */
export async function setSceneFields(jobId, i, fields) {
  const flat = {};
  for (const [k, v] of Object.entries(fields)) flat[k] = v === null || v === undefined ? "" : String(v);
  await r().hset(sceneKey(jobId, i), flat);
  await r().expire(sceneKey(jobId, i), TTL);
}

export async function getScene(jobId, i) {
  const h = await r().hgetall(sceneKey(jobId, i));
  return h && Object.keys(h).length ? h : null;
}

export async function getScenes(jobId, count) {
  const pipe = r().pipeline();
  for (let i = 0; i < count; i++) pipe.hgetall(sceneKey(jobId, i));
  const res = await pipe.exec();
  return res.map(([, h]) => (h && Object.keys(h).length ? h : null));
}

/** Atomic: returns true only for the FIRST caller that dispatches this batch. */
export async function tryClaimBatch(jobId, batchIndex) {
  const added = await r().sadd(batchGuardKey(jobId), String(batchIndex));
  await r().expire(batchGuardKey(jobId), TTL);
  return added === 1;
}
export async function dispatchedBatches(jobId) {
  const m = await r().smembers(batchGuardKey(jobId));
  return new Set(m.map(Number));
}

/** Atomic: returns true only for the FIRST caller that kicks off the stitch. */
export async function tryClaimStitch(jobId) {
  const ok = await r().set(stitchGuardKey(jobId), "1", "EX", TTL, "NX");
  return ok === "OK";
}

export async function destroy(jobId, count = 0) {
  const pipe = r().pipeline();
  pipe.del(jobKey(jobId), batchGuardKey(jobId), stitchGuardKey(jobId));
  for (let i = 0; i < count; i++) pipe.del(sceneKey(jobId, i));
  await pipe.exec();
}
